import assert from 'node:assert/strict';
import fs from 'node:fs';
import { FURNITURE_DATABASE,filterFurnitureCatalog } from '../src/core/furniture.js';
import { OBJECT_COLLECTIONS } from '../src/core/furniture/collections.js';
import { getObjectGeometryDefinition,objectGeometryBounds } from '../src/core/furniture/geometry-registry.js';
import { resolveObjectDimensions,objectPaperDimensions } from '../src/core/furniture/scaling.js';
import { createFurnitureAsset,furnitureAssetDXF,furnitureAssetSVG } from '../src/core/furniture-assets.js';
import { createConverterView,syncConverterDirectionUI } from '../src/ui/views/converter.js';
import { NAV_TOOL_LIST } from '../src/core/workspaces.js';
import { getWorkflowGuide } from '../src/core/tool-guides.js';
import {getObjectBrowseCatalog} from '../src/core/furniture/catalog.js';
import {QA_VIEWPORTS,QA_MODES} from '../scripts/qa-config.mjs';
let passed=0;
const check=(name,fn)=>{fn();passed++;console.log('PASS '+name);};
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-6,`${a} ≈ ${b}`);
check('Every official object is explicitly registered and has nontrivial finite CAD geometry',()=>{
  for(const item of FURNITURE_DATABASE){assert.equal(item.geometryStatus,'ready',item.id);assert.ok(getObjectGeometryDefinition(item.geometryId),item.id);const a=createFurnitureAsset(item),b=objectGeometryBounds(a.planGeometry);assert.ok(a.planGeometry.length>1,item.id);near(b.minX,0);near(b.minY,0);near(b.maxX,item.wCm/100);near(b.maxY,item.dCm/100);}
});
check('Unknown official IDs fail instead of silently becoming rectangles',()=>{assert.throws(()=>createFurnitureAsset({id:'missing-official',wCm:80,dCm:90}),/no registered geometry/);assert.equal(getObjectGeometryDefinition('missing'),null);});
check('Audited specialist objects use meaningful equipment symbols',()=>{for(const [id,family] of Object.entries({'basin-cloakroom':'basin','gym-elliptical':'elliptical','breathing-apparatus':'scba','fire-pole':'firePole','file-cabinet-4d':'cabinet','custody-toilet':'toilet','autoclave':'pressureAppliance','park-drinking-fountain':'drinkingFountain','mall-checkout':'checkout','track-400m':'track','helipad':'helipad'}))assert.equal(getObjectGeometryDefinition('object:'+id).family,family);assert.notDeepEqual(getObjectGeometryDefinition('object:bed-trundle').render(),getObjectGeometryDefinition('object:bed-twin-xl').render());assert.notDeepEqual(getObjectGeometryDefinition('object:grass-patch').render(),getObjectGeometryDefinition('object:groundcover-patch').render());assert.equal(getObjectGeometryDefinition('object:dining-4p-round').options.seats,4);});
check('Identical plan symbols browse once while every original ID remains represented',()=>{const browse=getObjectBrowseCatalog(),ids=browse.flatMap(i=>[i.id,...i.aliases.map(a=>a.id)]);assert.equal(new Set(ids).size,FURNITURE_DATABASE.length);assert.equal(ids.length,FURNITURE_DATABASE.length);const shapes=browse.map(i=>JSON.stringify(createFurnitureAsset(i).planGeometry));assert.equal(new Set(shapes).size,browse.length);assert.ok(filterFurnitureCatalog(browse,'fire station locker').length);assert.ok(filterFurnitureCatalog(browse,'police interview').length);});
const bed=FURNITURE_DATABASE.find(i=>i.id==='hospital-bed'),snapshot=JSON.stringify(bed);
check('Physical resize preserves catalog and updates real geometry and provenance',()=>{const a=createFurnitureAsset(bed,{widthMm:1100,depthMm:2400,heightMm:1200});const b=objectGeometryBounds(a.planGeometry);near(b.maxX,1.1);near(b.maxY,2.4);near(a.height,1.2);assert.equal(a.dimensionSourceType,'user-defined');assert.equal(JSON.stringify(bed),snapshot);});
check('Resized DXF coordinates use millimeters at 1:1',()=>{const dxf=furnitureAssetDXF(createFurnitureAsset(bed,{widthMm:1100,depthMm:2400}));assert.ok(dxf.includes('1100.0000'));assert.ok(dxf.includes('2400.0000'));assert.ok(!dxf.includes('2200.0000'));assert.ok(dxf.includes('A-FURN'));assert.equal(JSON.stringify(bed),snapshot);});
check('Resized SVG has physical dimensions and vector content',()=>{const svg=furnitureAssetSVG(createFurnitureAsset(bed,{widthMm:1100,depthMm:2400}));near(Number(svg.match(/width="([\d.]+)mm"/)[1]),1100);near(Number(svg.match(/height="([\d.]+)mm"/)[1]),2400);assert.ok(svg.includes('viewBox="0 -2400 1100 2400"'));assert.ok(!svg.includes('<image'));});
check('Paper scale affects only the readout',()=>{const a=createFurnitureAsset(bed,{widthMm:1100,depthMm:2400}),before=furnitureAssetDXF(a);assert.deepEqual(objectPaperDimensions(a.dimensions,50),{widthMm:22,depthMm:48});assert.deepEqual(objectPaperDimensions(a.dimensions,100),{widthMm:11,depthMm:24});assert.equal(furnitureAssetDXF(a),before);});
check('Proportion locks, height changes and reset are deterministic',()=>{const a=resolveObjectDimensions(bed,{widthMm:1100,preserveProportions:true});near(a.depthMm,bed.dCm*10*1100/(bed.wCm*10));const b=resolveObjectDimensions(bed,{depthMm:2400,preserveProportions:true});near(b.widthMm,bed.wCm*10*2400/(bed.dCm*10));assert.throws(()=>resolveObjectDimensions(bed,{widthMm:1,depthMm:2,preserveProportions:true}));assert.equal(resolveObjectDimensions(bed).modified,false);assert.throws(()=>resolveObjectDimensions(bed,{widthMm:NaN}));assert.throws(()=>resolveObjectDimensions(bed,{depthMm:-1}));});
for(const collection of OBJECT_COLLECTIONS)check('Browse collection '+collection.label,()=>assert.ok(filterFurnitureCatalog(FURNITURE_DATABASE,'','all','default',collection.id).length));
for(const query of ['hospital bed','fire station locker','police interview','park bench','palm tree','luxury sofa','street light','mall checkout','wheelchair','outdoor bbq'])check('Search '+query,()=>assert.ok(filterFurnitureCatalog(FURNITURE_DATABASE,query).length,query));
for(const ids of [['tree-palm-mature','tree-olive-mature','tree-pine-mature','tree-oak-mature'],['grand-piano','sofa-chesterfield','wingback-chair','bathtub-corner-jacuzzi'],['hospital-bed','hospital-bed-icu','stretcher','dental-chair']])check('Recognizable compositions differ: '+ids.join(', '),()=>{
  const signatures=ids.map(id=>{const definition=getObjectGeometryDefinition('object:'+id);return JSON.stringify(definition.render());});assert.equal(new Set(signatures).size,ids.length);
});
check('Optional clearance keeps its own layer after resize',()=>{const a=createFurnitureAsset({...bed,clearance:90},{widthMm:1100,depthMm:2400});assert.ok(!furnitureAssetDXF(a).includes('A-CLEARANCE'));assert.ok(furnitureAssetDXF(a,{includeClearance:true}).includes('A-CLEARANCE'));near(objectGeometryBounds(a.clearanceGeometry).maxX,2);});
check('Converter UI sync follows programmatic direction state',()=>{
  const field=()=>({textContent:'',value:''}),dom={converterInputBadge:field(),converterOutputBadge:field(),converterFlowFrom:field(),converterFlowTo:field(),converterResultLabel:field(),converterDirectionDescription:field(),converterMathFormula:field()};const state={direction:'real_to_drawing',scaleRatio:50};syncConverterDirectionUI(state,dom);assert.equal(dom.converterInputBadge.textContent,'Real measurement');assert.equal(dom.converterFlowTo.textContent,'Drawing size');assert.ok(dom.converterMathFormula.textContent.includes('÷'));state.direction='drawing_to_real';syncConverterDirectionUI(state,dom);assert.equal(dom.converterInputBadge.textContent,'Measurement on drawing');assert.equal(dom.converterFlowTo.textContent,'Real size');assert.ok(dom.converterMathFormula.textContent.includes('×'));
});
check('Actual calculation synchronizes external navigation and clears stale error results',()=>{
  const field=value=>({value,textContent:'',classList:{add(){},remove(){}}});const state={direction:'real_to_drawing',precision:3};const dom={scaleRatioInput:field('50'),converterInputVal:field('5'),converterInputUnit:field('m'),converterOutputUnit:field('mm'),converterInputBadge:field(),converterOutputBadge:field(),converterResultVal:field(),converterResultUnit:field(),converterFlowFrom:field(),converterFlowTo:field(),converterExplanation:field(),converterResultLabel:field()};
  const previous=globalThis.document;globalThis.document={getElementById:()=>null};try{const view=createConverterView({state,dom,setUnifiedResultState:()=>{},AudioService:{playSwapSound(){}}});view.getController().calculateConverter();assert.equal(Number(dom.converterResultVal.textContent),100);assert.equal(dom.converterInputBadge.textContent,'Real measurement');state.direction='drawing_to_real';dom.converterInputVal.value='100';dom.converterInputUnit.value='mm';dom.converterOutputUnit.value='m';view.getController().calculateConverter();assert.equal(Number(dom.converterResultVal.textContent),5);assert.equal(dom.converterInputBadge.textContent,'Measurement on drawing');dom.converterInputVal.value='';view.getController().calculateConverter();assert.equal(dom.converterResultVal.textContent,'—');assert.equal(dom.converterExplanation.textContent,'');}finally{globalThis.document=previous;}
});
check('Current navigation, help and removed editor components agree',()=>{assert.ok(NAV_TOOL_LIST.every(t=>t.toolId!=='plan'&&getWorkflowGuide(t.toolId)));for(const file of ['src/ui/views/plan.js','src/core/plan-canvas.js','src/ui/components/ribbon.js','src/ui/components/palette.js','src/ui/components/cpanels.js','scripts/qa_plan_canvas_accuracy.py'])assert.ok(!fs.existsSync(file));});
check('Responsive QA configuration covers the current registry at all seven sizes',()=>{assert.deepEqual(new Set(QA_MODES),new Set(['home',...NAV_TOOL_LIST.map(t=>t.toolId)]));assert.equal(QA_VIEWPORTS.length,7);assert.ok(QA_VIEWPORTS.some(([w,h])=>w===390&&h===844));assert.ok(QA_VIEWPORTS.some(([w,h])=>w===1920&&h===1080));assert.ok(!QA_MODES.some(m=>['plan','workspace','expression','chains','multiscale'].includes(m)));});
check('Generated responsive report describes the current live navigation',()=>{const report=JSON.parse(fs.readFileSync('qa-report.json','utf8'));assert.deepEqual(new Set(report.modes),new Set(QA_MODES));assert.deepEqual(report.viewports,QA_VIEWPORTS);for(const [w,h] of QA_VIEWPORTS)assert.ok(QA_MODES.every(mode=>report.checks[`${w}x${h}`]?.[mode]));assert.equal(report.summary.failures.length,0);assert.equal(report.errors.length,0);});
console.log(`Object follow-up: ${passed} passed, 0 failed.`);
