import { ensureConcept, createDesignDriver } from '../../core/concept.js';
import { ensureStructuredResearch } from '../../core/research-workspace.js';
import { ensureSiteAnalyses } from '../../core/site-analysis.js';
import { bubbleDiagramSVG } from '../../core/analysis-diagrams.js';
import { requestResearchAI } from '../../services/research-assistant.js';
import { workspaceEscape, workspaceTextField, workspaceSave, workspaceRequireProject } from '../components/workspace-ui.js';

export function createConceptView(context) {
  function render() {
    const host=document.getElementById('concept-workspace');if(!host)return;
    const project=workspaceRequireProject(context,host);if(!project)return;
    const c=ensureConcept(project),r=ensureStructuredResearch(project),analyses=ensureSiteAnalyses(project);
    const nodes=[...new Set(c.spatialRelationships.flat())];
    host.innerHTML=`<div class="companion-workspace"><aside class="companion-index"><h3>Design drivers</h3><p>Research finding → site implication → driver → concept.</p>${c.drivers.map(d=>`<article><p>${workspaceEscape(d.text)}</p><small>${workspaceEscape(r.claims.find(f=>f.id===d.findingId)?.text||'')} ${workspaceEscape(analyses.find(a=>a.id===d.siteAnalysisId)?.title||'')}</small><button type="button" data-delete-driver="${d.id}">Remove</button></article>`).join('')}${workspaceTextField('concept-driver-text','New driver','',{rows:2})}<label>Research finding<select id="concept-finding" class="calc-select"><option value="">No finding link</option>${r.claims.map(f=>`<option value="${workspaceEscape(f.id)}">${workspaceEscape(f.text.slice(0,100))}</option>`).join('')}</select></label><label>Site implication<select id="concept-site" class="calc-select"><option value="">No site link</option>${analyses.filter(a=>a.designImplication).map(a=>`<option value="${a.id}">${workspaceEscape(a.title)}</option>`).join('')}</select></label><button type="button" id="concept-driver-add" class="action-tool-btn">Add driver</button></aside><main class="archi-card companion-card"><h2>Concept</h2>${workspaceTextField('concept-statement','Concept statement',c.statement)}${workspaceTextField('concept-keywords','Keywords (comma separated)',c.keywords.join(', '),{type:'text'})}<div class="companion-form-grid">${['goals','constraints','precedentInspiration','massingIdeas','materialIdeas','narrative'].map(k=>workspaceTextField('concept-'+k,k.replace(/([A-Z])/g,' $1'),c[k])).join('')}</div>${workspaceTextField('concept-relationships','Spatial relationships: one From → To per line',c.spatialRelationships.map(pair=>pair.join(' → ')).join('\n'))}<div class="companion-actions"><button type="button" id="concept-save" class="action-tool-btn primary">Save concept</button><button type="button" id="concept-ideation" class="action-tool-btn">Explore ideas with AI</button><button type="button" id="concept-image" class="action-tool-btn">Request conceptual image</button></div><p id="concept-ai-status" role="status"></p>${workspaceTextField('concept-ai-draft','AI ideas — review before using','',{rows:6})}<button type="button" id="concept-ai-use" class="action-tool-btn">Use reviewed ideas as narrative</button><div class="analysis-visual">${bubbleDiagramSVG(nodes,c.spatialRelationships)}</div></main></div>`;
    const get=id=>host.querySelector('#'+id);
    get('concept-save').addEventListener('click',()=>{
      const pairs=get('concept-relationships').value.split('\n').filter(Boolean).map(line=>line.split(/→|->/).map(s=>s.trim()));
      if(pairs.some(p=>p.length!==2||p.some(s=>!s))){context.showToast('Use From → To for every relationship','error');return;}
      if(workspaceSave(context,p=>{const data=ensureConcept(p);for(const k of ['statement','goals','constraints','precedentInspiration','massingIdeas','materialIdeas','narrative'])data[k]=get('concept-'+k).value;data.keywords=get('concept-keywords').value.split(',').map(s=>s.trim()).filter(Boolean);data.spatialRelationships=pairs;}).ok){context.showToast('Concept saved','success');render();}
    });
    get('concept-driver-add').addEventListener('click',()=>{const result=createDesignDriver({text:get('concept-driver-text').value,findingId:get('concept-finding').value,siteAnalysisId:get('concept-site').value},project);if(!result.ok){context.showToast(result.error,'error');return;}if(workspaceSave(context,p=>ensureConcept(p).drivers.push(result.driver)).ok)render();});
    host.querySelectorAll('[data-delete-driver]').forEach(b=>b.addEventListener('click',()=>{workspaceSave(context,p=>{const data=ensureConcept(p);data.drivers=data.drivers.filter(d=>d.id!==b.dataset.deleteDriver);});render();}));
    get('concept-ideation').addEventListener('click',async()=>{const b=get('concept-ideation');b.disabled=true;get('concept-ai-status').textContent='Exploring…';try{const result=await requestResearchAI(context.state.ai?.router,context.projectStore.getProject(),{task:'concept'});get('concept-ai-status').textContent=result.ok?'Unverified AI ideas':result.message;if(result.ok)get('concept-ai-draft').value=result.text||'';}finally{b.disabled=false;}});
    get('concept-ai-use').addEventListener('click',()=>{const text=get('concept-ai-draft').value.trim();if(text&&workspaceSave(context,p=>{ensureConcept(p).narrative=text;}).ok)render();});
    get('concept-image').addEventListener('click',async()=>{const router=context.state.ai?.router;if(!router){get('concept-ai-status').textContent='Configure an image-capable provider first';return;}const result=await router.runAIJob('conceptImage',{userMessage:'Create a conceptual architecture image for '+get('concept-statement').value});get('concept-ai-status').textContent=result.ok?'Conceptual output: '+(result.text||'Review the provider result'):(result.message||'Image generation is unavailable for this provider.');});
  }
  return {id:'concept',mount(){},onModeEnter:render,getController:()=>({render})};
}
